if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
BiocManager::install("affyPLM")
BiocManager::install("vsn")
BiocManager::install("limma")
BiocManager::install("oligo")
BiocManager::install("canine2.db")
BiocManager::install("topGO")
BiocManager::install("Rgraphviz")
BiocManager::install("canine2.db")
BiocManager::install("annotate")

install.packages("gplots")
install.packages("ggplot2")
install.packages("MASS")
install.packages('shiny')
install.packages("magick")
install.packages("remotes")
